# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180705_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=False, verbose_name='Odnośnik'),
        ),
    ]
